options:
  logging: CLOUD_LOGGING_ONLY
steps:
  #Step 1
  #using code build command to build image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'sohail:apachev1', '.']
  #Step 2
  # do SAST in build container image with trivy
  - name: 'aquasec/trivy:latest'
    args: ['image' ,'--severity' ,'HIGH,CRITICAL' ,'--format', 'json',  '--output' , '/workspace/soh_imagescan.json','--exit-code','1' ,'sohail:apachev1']
    
  # STEP 3 upload trivy result to GSC
  - name:  'google/cloud-sdk'
    args: ['gsutil', 'cp','/workspace/soh_imagescan.json','gs://vodafone-trivy-scan-results/containers/']
  
  #Step 4
  #Creating container
  - name: 'gcr.io/cloud-builders/docker'
    args: ['run', '-idt', '--name', 'sohctl',
     '-p' ,'8008:80', '--rm' ,'sohail:apachev1'
    ]