options:
  logging: CLOUD_LOGGING_ONLY
steps:
  #Step 1
  #using code build command to build image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'sohail-app:v1', '.']

  #Step 2
  # do SAST in build container image with trivy
  - name: 'aquasec/trivy:latest'
    args: ['image' ,'--severity' ,'HIGH,CRITICAL' ,'--format', 'json',  '--output' , '/workspace/soh_imagescan.json','--exit-code','0' ,'sohail-app:v1']
    
  # STEP 3 upload trivy result to GSC
  - name:  'google/cloud-sdk'
    args: ['gsutil', 'cp','/workspace/soh_imagescan.json','gs://vodafone-trivy-scan-results/containers/']
  
  #Step 4
  #Creating container
  - name: 'gcr.io/cloud-builders/docker'
    args: ['run', '-idt', '--name', 'sohctl',
     '-p' ,'8008:80', '--rm' ,'sohail-app:v1'
    ]

  #Step 5 App running status by logging into same container and doing curl
  - name: 'gcr.io/cloud-builders/docker'
    args: ['exec', 'sohctl', 'curl', '-f', 'http://localhost/health.html']

  #Step 6 tag docker image into artifact registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'sohail-app:v1', 'asia-docker.pkg.dev/vodafone-devsecops/vodafone-webapp-images/sohail-app:v1']

  #Step 7 Push image into artifact registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-docker.pkg.dev/vodafone-devsecops/vodafone-webapp-images/sohail-app:v1']

  # Step 8  Deploy sample nginx container on GKE
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - apply
      - -f
      - sohl-app-deploy.yaml
    env: # passing k8s info
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
      - 'CLOUDSDK_CONTAINER_CLUSTER=my-first-cluster-1'

  # Step 9  Deploy check
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - get
      - deploy,pods
    env: # passing k8s info
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
      - 'CLOUDSDK_CONTAINER_CLUSTER=my-first-cluster-1'